### ISSUE TITLE
Node parent sanity check prevents loading files created with UniGLTF-1.27

### ISSUE THREAD

**Issue by WickedSmoke** [jkuhlmann/cgltf#222]
Parse fails on files generated with UniGLTF-1.27 because `data->scenes[i].nodes[j]->parent` is not NULL at line 6659 in cgltf_fixup_pointers().

The following is the JSON scene graph, which should be valid as glTF doesn't declare parents, only children.  The loader should see a scene with a single node and ignore the unreferenced "tmpParent". 

```
    "nodes": [  
        {       
            "children": [ 1 ],
            "name": "tmpParent",
            "rotation": [ 0, 0, 0, 1 ],
            "scale": [ 1, 1, 1 ],
            "translation": [ 0, 0, 0 ]
        },
        {
            "mesh": 0,
            "name": "fountainCenter",
            "rotation": [ 0, -0.707106769, 0, 0.7071068 ],
            "scale": [ 1, 1, 1 ],
            "translation": [ 0, 0, 0 ]
        }
    ],
    "scene": 0,
    "scenes": [ { "nodes": [ 1 ] } ]
```

**Comment by WickedSmoke** [comment]
I'm not a user of that exporter but there are assets floating around the net that do.  I'll just be disabling that check in my version of cgltf.h so that I can load models.

**Comment by WickedSmoke** [comment]
Adding a new error code that indicates "the data was loaded OK, but it does not strictly follow spec." would be good here.  Something that would help users know why the data isn't loading without having to crack open a debugger as I did.  An even more specific error (invalid scene root node) might be better.

**Comment by zeux** [comment]
We already return "cgltf_result_invalid_gltf" for this which has the broad meaning you suggest. When the spec is violated, the resulting data may be internally inconsistent, for example for this specific issue, obviously we return from the function early so the data isn't really usable, but if we didn't, the parent links would be invalid for some nodes as the code doesn't necessarily select the "right" parent in case the file violates the invariants.

There are a lot of different error conditions for why the spec could be violated. In general I think the expectation is that the loaders return the error if the file isn't conformant (when that prevents correct operation - like it does in this case, because we can't establish the correct "parent" link otherwise!), and further diagnostics can be retrieved by running the official glTF validator.

**Comment by WickedSmoke** [comment]
Thanks for the explanation.  I'm just starting to use this format so I wasn't aware of gltf_validator.  It does look like the issue is fixed in newer versions of UniGLTF.
