### ISSUE TITLE
Possible to have individual flags for metallic and roughness?

### ISSUE THREAD

**Issue by chaoticbob** [jkuhlmann/cgltf#225]
Hi, I posted [issue#1956](https://github.com/KhronosGroup/glTF-Blender-IO/issues/1956) over on the glTF-Blender-IO repo with regards to handling of metallic and roughness properties. **TL;DR;** when a material doesn't have metallic, the exporter is writing 1 into the exported texture as opposed to the value set by the node. 

This got me wondering, currently in `cgltf` there is a combined flag that checks to see if a material `has_metallic_roughness`. I know that the texture source is one texture for both metallic and roughness, but was wondering if there are cases where one is present but not the other? For instance if a wood material only has roughess (along with baseColor and normal) but not metallic. 

My inclination (which may be wong in terms of the spec) is that if the material only has roughness, there should be a texture for roughness and `metallicFactor` of 0. Which is what I'm seeing in the export:
```
			"pbrMetallicRoughness":{
				"baseColorTexture":{
					"index":1
				},
				"metallicFactor":0,
				"metallicRoughnessTexture":{
					"index":2
				}
			}
```

I don't see a flag in the `cgltf` API to check for metallic or roughness individually. Am I missing or misundersatnding something here?

**Comment by zeux** [comment]
The way you would check the condition you're asking about is `material->has_pbr_metallic_roughness && material->pbr_metallic_roughness.metallic_factor > 0` and `material->has_pbr_metallic_roughness && material->pbr_metallic_roughness.roughness_factor > 0`, respectively.

`has_pbr_metallic_roughness` specifically refers to the presence of `pbrMetallicRoughness` node in glTF material file; cgltf mirrors the structure of glTF files pretty much one to one, so since glTF files don't have metallic and roughness separated, other than through factors, that's how cgltf represents this as well.

**Comment by zeux** [comment]
Let's ignore cgltf for now, as I said it tries to give a 1-1 semantic mirror of the glTF file.

The way glTF metallic roughness node works is that for every pixel, the metalness value is computed as `metallicFactor * textureSample(metallicRoughnessTexture, uv).b`, and roughness value is computed as `roughnessFactor * textureSample(metallicRoughnessTexture, uv).g`. When texture is absent, the texture sample is assumed to return `(1, 1, 1, 1)`. When either factor is absent, it is assumed to be 1. See https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#metallic-roughness-material.

A factor is *not* ignored when a texture is present. A factor that is absent is indistinguishable from a factor that is specified and equal to 1.

As such, you can determine the definite absence of metalness (if the goal is to skip some computations) by checking if metalnessFactor is exactly 0 - even if texture is present, that will nullify whatever values the texture has.

If the factor is not 0 or absent (which means it's 1), and the texture is present, you can't definitively say whether any pixels of the mesh must be rendered as a metallic material - this requires analyzing the blue channel of the texture and seeing if all pixels are 0, which glTF file doesn't provide anywhere.

Hopefully that clarifies this? Getting back to cgltf, since absence of metallicFactor is equivalent to metallicFactor being specified as 1, cgltf doesn't store the presence of the factor in source document anywhere because from the spec perspective it doesn't matter if it exists.

**Comment by chaoticbob** [comment]
That's a helpful explanation. Thanks!

I had forgotten that the factors acts as multiplier in the cases I stated above. In thinking about it, the ambiguous case(s) will need to be addressed with workflow requirements.
