### ISSUE TITLE
File system options

### ISSUE THREAD

**Issue by maluoi** [jkuhlmann/cgltf#94]
First off, thanks for an incredible library! Very much enjoying using it :)

Today I had a platform issue with the fopen call, probably something to do with UWP. This is easily avoided with all-in-one gltf files by just directly using `cgltf_parse` instead of `cgltf_parse_file` and passing file data I've loaded myself. Unfortunately, `cgltf_load_buffer_file` also uses fopen directly! This trips up any gltf files with references in them.

I would love to see something like file read callbacks in cgltf_options! This would solve my problem quite nicely :)

**Comment by jkuhlmann** [comment]
To make sure we get the API right, what where the functions you ended up using for opening and reading files?

**Comment by maluoi** [comment]
In this case, swapping out to fopen_s worked well enough for me. However, for a broader perspective, I've often toyed with the idea of using something similar to this library in the loger run: https://icculus.org/physfs/

**Comment by prideout** [comment]
+1 for this feature request.  In its current form, `cgltf_load_buffers` has limited usefulness on Android and Emscripten platforms since they do not have file systems.

Using a callback argument might work well.  The user would provide a function that consumes a URI string and produces a void* memory blob and a cgltf_size.

Note that this feature would not only be useful for buffers but for images as well.

**Comment by LxLasso** [comment]
It would be great if the void* memory blob wasn't then freed but 'unlocked' using another callback. That way you could use memory mapped io on systems that support it and not have to load the entire file to a memory blob.

Perhaps something along these lines?

```
struct file_data_handle
{
   void* memory_blob;
   cgltf_size memory_blob_size;
};

file_data_handle* read_file_callback(char* uri);
close_file_callback(file_data_handle*);
```

**Comment by prideout** [comment]
I was thinking we need only one callback, and its implementation need not read an entire blob, it simply maps a uri string to void* / size pair, which cgltf uses to populate the two relevant fields in cgltf_buffer:

```cgltf_bool read_buffer_fn(const char* uri, void** buffer, cgltf_size* size);```

Clients will commonly provide a void* value that points to a memory blob, but they can actually point the void* to anything they want, including an opaque stream handle.

I don't understand the need for an `unlock` or `close` callback, since cgltf itself does not use the void*, it simply stashes it inside the cgltf_buffer structure.  Were you thinking that the unlock callback would get called during `cgltf_free`?  I feel that buffers are owned by client, so it's their responsibility to track them and free them.

**Comment by LxLasso** [comment]
At the moment `cgltf_free(..)` frees `cgltf_buffer.data`. If `read_buffer_fn(..)` hasn't allocated that memory but rather acquired a pointer to memory from the system, a mechanism is required to prevent `cgltf_free(..)` from attempting to free it. So I was thinking of wrapping that `void*` into something managed, but now that you brought up ownership I'm having second thoughts about my suggestion .. :-/

**Comment by prideout** [comment]
Good point, I guess this feature implies the addition of a new bool field to `cgltf_buffer` to mark client ownership, so that `cgltf_free()` will skip it.

Or, instead of a bool, we add a nullable free callback that defaults to `memory_free`, which is similar what you were initially suggesting.  :)

**Comment by jkuhlmann** [comment]
I have a first draft in PR #102. What do you think?
